# Generated by Django 4.2.4 on 2023-11-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_abroad_app', '0003_application_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='signed_form_upload',
            field=models.FileField(blank=True, null=True, upload_to='signed_forms/'),
        ),
    ]
